server.port=8081
spring.jpa.database=mysql
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/sport_shop_java
spring.datasource.username = oboe_user
spring.datasource.password = your_password
jwt.secret=Shop.2026

#spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop
logging.level.com.sportshop.filter=INFO
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true